### ISSUE TITLE
Epic 5 (Discovery): Interactive Filtering

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#12]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.
### Expectation:
Interactive filtering options display the effects of filter values on the outputs
### Priority:
Medium
### Dependencies:
None
### Description:
Current filtering options are limited and can only be reviewed by issuing server requests and updating with a button-press, which retrieves updated outputs from the backend services. This task would be to outline and possibly implement a solution for either demonstrating the effect of individual layer filtering, or "on-the-fly" filtering which is reactive and directly demonstrates the implications of each of the individual filters on data.
### Scope: 
The scope of this process will depend on the results of the discovery process.
### Requirements:
None
### Success Criteria:
Users are able to visualise the effects of their individual filter values

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV & @gclapp1 
I had thought about this:
Currently the filtering results are displayed only when the zone scores are calculated by pressing the generate zones buttons.
I would suggest that we keep the zone calculation only happening when we press the "generate zones" button.
But for the filtering, we have the "suitable areas" raster that is displayed to indicated zones that are filtered out.
I suggest that at the bottom of the filters we add a button saying "apply filters" and a check box for auto applying the filtering. This will make sure the "suitable areas" layer is displayed on the map and will make it easier to find out which zones are filtered out and will have the benefit of viewing the area of interest dynamically without the delay of waiting for each zone score to generated.
Let me know what you think so I can start implementing this feature.

**Comment by ClaraIV** [comment]
I am not sure this works as expected. 

Please see below Angola_onshore wind: nothing is displayed



![Image](https://user-images.githubusercontent.com/9391517/225683924-55331c18-bc5e-4e72-9921-650bce7c4863.png)

The same value range/ same parameters show a complete raster on the published tool:



![Image](https://user-images.githubusercontent.com/9391517/225684115-4359d5b3-937f-4980-a9ba-7fa2ac54e4bb.png)

**Comment by ClaraIV** [comment]
furthermore, I believe that the filtering resulted in other bugs, as the results the tool generate now are radically different (almost not filtered at all) than what we obtain using the original tool.
Please see the new tickets on the matter

**Comment by ClaraIV** [comment]
I don't see the "Distance to" layers being displayed, is this still in the works?

**Comment by NEDJIMAbelgacem** [comment]
> I don't see the "Distance to" layers being displayed, is this still in the works?

This has been addressed

**Comment by ClaraIV** [comment]
@akshay2408 @dimasciput 
I still do not see that this is working properly. please see below.
For offshore wind -Romania, the Wind Speed filter (>7m/s) shows no data; however, I know for a fact there are 2 areas with wind speed >7m/s and this is resulted also from running the tool, please see the results in pink with the same wind speed filter.



![Image](https://user-images.githubusercontent.com/9391517/236492637-ee4ac86d-5331-4d5b-8909-eb25d583cb97.png)



![Image](https://user-images.githubusercontent.com/9391517/236493123-6144169d-f546-410b-b60e-59f28ed6ff21.png)

**Comment by akshay2408** [comment]
Hi @ClaraIV 
Could you please check this again. I just checked and I think the area is visible, also in 1st screenshot we have zone type as Boundaries and resource is Offshore.
But last week in one of the ticket we removed the Boundaries option for offshore.
https://github.com/kartoza/rezoning-2-project/issues/5

**Comment by LunaAsefaw** [comment]
@ClaraIV I was going through the Rezoning user guide and saw this.
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/7732cc4f-0196-4756-af1e-d022965e94d4)

Let's say you chose solar for Afghanistan and you set the filters to specific values, then decide you want to assess Albania, should the parameter values change or should they be the same values you had for Afghanistan and user can click on reset value to get default values for Albania?

**Comment by ClaraIV** [comment]
@LunaAsefaw RE your previous comment: the range of value >7 generates results; that means that I should be able to see the offshore wind resource layer with the filter set value>7 at tool initiation phase; this is what I tested and failed; please let me know if this is clear

RE your last comment, that seems fine, and it is not connected to the use case I presented;

**Comment by LunaAsefaw** [comment]
@ClaraIV When I use the parameters you used (25km) I also get 2 suitable areas, See below:
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/f23690dc-573a-4a19-be8d-478eb7cb3927)

Additionally, when I change the zone size to 50 Km, I also get two suitable areas:
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/bc09a96d-74dd-435a-aa77-bf43d145ad7b)

The image you sent that has no areas returned uses boundaries for the zone type and we said if offshore wind is selected, boundary is not an option so offshore data only has 25 or 50 km as the options. In fact even if I wanted to test it, I couldn't because boundaries was removed from the options for the users to select.

RE the second comment, I saw this in the user guide but I don't think that is how the system is built. If I changed countries, the inputs change to the minimum and maximums relating to the changed country. So my concern is, what method is preferred? The document mentions using the maximum and minimums as the range but also mentions keeping inputs when countries are changed, which is conflicting.

**Comment by ClaraIV** [comment]
@LunaAsefaw , you are missing the point - the point is that the tool should **show the wind speed** (the resource layer) upon tool initiation - forget the unit of analysis from my 2nd screenshot, it is not important and I did it quickly for demonstration. Perhaps it is better to leave this ticket for discussion in the team meeting

**Comment by ClaraIV** [comment]
@LunaAsefaw the Land Use/Land Cover filter doesnt seem to work, it doesnt display any data - can you kindly check?
This layer should have been updated with the latest dataset, we provided a link to that - I wonder if there's a bug in its ingestion

![image](https://github.com/kartoza/rezoning-2-project/assets/9391517/d9fdfd88-82d2-4091-ad7a-74cec0c8a2fb)

**Comment by LunaAsefaw** [comment]
Thanks for picking this up, my apologies for not noticing @ClaraIV. I played around a bit to see what the issue is so we have a clear problem statement for @dimasciput and found the following:
So when I deactivate the toggle, all the land covers found in the dropdown list are included so it shows this:
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/8362ec57-3364-4488-bd9c-60722ea41688)

Then I switch the toggle on and nothing shows, as seen in Clara's screenshot above.  I thought it is because the land covers found are not selected in the list but when I see the list, water bodies and urban areas are selected and were actually found in the area yet they do not return anything. 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/6d22d6ea-f10e-41e1-9159-c2ccc030801f)

Then I selected every landcover on the dropdown list and then the toggle worked
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/4b92457b-72ae-4ec5-be9a-2db747e1b603)

So the bug with this function is that it does not allow selection of specific land covers, it only displays either all the land covers or none.

**Comment by ClaraIV** [comment]
I actually think the classes are filtered out, if they wouldnt be filtered,
the entire area would be covered. Since we see patches of empty land, that
means that the filter is working. If there would be “no data”, black pixels
would be displayed.
@dimasciput

**Comment by ClaraIV** [comment]
You can have a look st the ESA land cover dataset online, they have a web
app and you can visualize each country to see how it should look with all
the classes selected. This can give you an idea on how the filter is working

**Comment by LunaAsefaw** [comment]
The issue has been fixed, when I just click on the 'show' icon, the land cover shows

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/ed6c3e59-e4f5-4351-81ef-bb54b6866f2a)

If I add more land cover options from the drop down, it adds and displays without issues. See below, initially water bodies was not selected and now that it is, it is displayed


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/e1489628-83c4-488f-9de3-f47bfeec47e4)

Lastly, when the toggle is switched off, all the layers are displayed successfully


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/86e3f6b6-571c-4595-b264-9d5199776447)

Additionally, the interactive filtering issue seen with selecting UNESCO (reported in #13) is fixed


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/358b9fda-090f-4279-8192-682ef5e92f13)
